### ISSUE TITLE
Namespace dirs imports

### ISSUE THREAD

**Issue by DaPotatoMan** [unplugin/unplugin-auto-import#265]
### Clear and concise description of the problem

Namespace all imports from a directory. Instead of using `foo()`, use `api.foo()` to import functions.

Why -
- Avoid name collisions
- Tree shaking

### Suggested solution

> Config:
```ts
dirs: [
  'src/logic/composables',
  ['api', 'src/logic/requests']
]
```

> src/logic/requests/index.ts
```ts
export function fetchBlogs() {}
export function fetchProducts() {}
```

> Then in project files:
```ts
api.fetchBlogs()
api.fetchProducts()

```

#### Under the hood:

```ts
export function fetchBlogs() {}
export function fetchProducts() {}
```

```ts
import { fetchBlogs as api_fetchBlogs, fetchProducts as api_fetchProducts } from '...'

api_fetchBlogs()
api_fetchProducts()
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ddosakura** [comment]
you can try this:

config:

```ts
dirs: [ 'src/apis/']
```

`src/apis/index.ts`:

```ts
import * as api from "...";
export { api };
```

`auto-imports.d.ts`:

```ts
// Generated by 'unplugin-auto-import'
export {}
declare global {
  const api: typeof import('./src/apis/index')['api']
}
```
