### ISSUE TITLE
Using auto-imported functions in `.astro` files throws an error

### ISSUE THREAD

**Issue by jiangmaniu** [unplugin/unplugin-auto-import#352]
### Describe the bug

![image](https://user-images.githubusercontent.com/50100681/228274095-92389b1a-bfe9-487c-b10f-998476dc4afb.png)

If you uncomment `console.log(oldFontSizeMap)` according to the comment, the following error will be reported

![image](https://user-images.githubusercontent.com/50100681/228274462-b5289082-64e7-4760-b439-a4f86aa74ff8.png)

### Reproduction

https://stackblitz.com/edit/github-dp5zp2-j1e9uu?file=src/pages/index.astro

### System Info

```Shell
x
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@jiangmaniu your configuration is wrong, you also need to add `include` option adding `.astro` files, by default not being transformed, check [this SB reproduction](https://stackblitz.com/edit/github-dp5zp2-jfdprv?file=astro.config.mjs)

![imagen](https://github.com/unplugin/unplugin-auto-import/assets/6311119/4d6e9f62-295d-49a0-923a-8727b03f5aad)

**Comment by CapitaineToinon** [comment]
Ah yes of course, that fixed it for me. Thanks!
