### ISSUE TITLE
Auto importing custom types from a Directory

### ISSUE THREAD

**Issue by nattyluke** [unplugin/unplugin-auto-import#422]
### Clear and concise description of the problem

I have a types Directory with some interfaces and types which i want to be imported globally.
I dont know if this situation is covered by https://github.com/antfu/unplugin-auto-import/issues/61.
adding 'src/types' to the dirs array doesnt do anything. Im on 0.16.6.

### Suggested solution

Types should be able to be made global as other functions/classes

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by LeoKun1231** [comment]
Is automatic import of custom types supported now?

**Comment by camhammel** [comment]
Was this functionality added? I can't seem to get it working within the `import` or `dirs` config

**Comment by LefanTan** [comment]
I'm observing the same behavior as @camhammel, type exports aren't being added to the global `.ts`
