### ISSUE TITLE
Unable to customise the introduction of namespace

### ISSUE THREAD

**Issue by yveeven** [unplugin/unplugin-auto-import#434]
### Describe the bug

Using `zod` does not automatically introduce `namespace`, which means that the `z.inter` type cannot be used.
Minimum implementation can be viewed

### Reproduction

https://codesandbox.io/s/hungry-galileo-vnh8ps?file=/src/pages/Index.vue

### System Info

```Shell
System:
    OS: Linux 5.13 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 5.11 GB / 62.72 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nakorndev** [comment]
I have this problem too. This is my nuxt.config.ts custom imports value.

```.ts
imports: {
  presets: [
    {
      from: 'zod',
      imports: ['z'],
    },
    {
      from: '@vee-validate/zod',
      imports: ['toTypedSchema'],
    },
  ],
},
```

![image](https://github.com/unplugin/unplugin-auto-import/assets/5706431/ed5f51ea-e481-4aae-be14-490cadadbffd)

**Comment by nakorndev** [comment]
I have the same problem. After reviewing the `readme.md` file for a while, I think the temporary solution is to use an alias with `type: true`.

![image](https://github.com/unplugin/unplugin-auto-import/assets/5706431/2110f9e5-160e-4039-b54e-1a6b1f04e486)

**Comment by yveeven** [comment]
It's probably not as bad as if I just added the global
```
export * from 'zod'
export as namespace z
```

**Comment by yveeven** [comment]
Probably not as good as a global declaration
```
export * from 'zod'
export as namespace z
```

**Comment by yveeven** [comment]
> 我也有同样的问题。在查看了`readme.md`文件一段时间后，我认为临时解决方案是使用别名`type: true`。
> 
> ![image](https://user-images.githubusercontent.com/5706431/279579670-2110f9e5-160e-4039-b54e-1a6b1f04e486.png)

Probably not as good as a global declaration
``
export * from 'zod'
export as namespace z
```

**Comment by yveeven** [comment]
> I have the same problem. After reviewing the `readme.md` file for a while, I think the temporary solution is to use an alias with `type: true`.
> 
> ![image](https://user-images.githubusercontent.com/5706431/279579670-2110f9e5-160e-4039-b54e-1a6b1f04e486.png)

Probably not as good as a global declaration
```
export * from 'zod'
export as namespace z
```
