### ISSUE TITLE
vue component The page is not rendered.

### ISSUE THREAD

**Issue by xzhdev** [unplugin/unplugin-auto-import#438]
### Clear and concise description of the problem

I use <component :is="'el-form'"> when using encapsulated components, 
and the Elementplus component does not take effect，The page does not show el-form.<img width="870" alt="image" src="https://github.com/unplugin/unplugin-auto-import/assets/102580603/50b8b71a-cee9-4139-be6b-3c87f837e34b">

### Suggested solution

Can you support it

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lishaobos** [comment]
you might need https://github.com/unplugin/unplugin-vue-components, and refer to https://github.com/unplugin/unplugin-vue-components/issues/643
