### ISSUE TITLE
template标签与script标签的自导导入识别规则不一致

### ISSUE THREAD

**Issue by itmanyong** [unplugin/unplugin-auto-import#440]
### Describe the bug

* 以`$`等特殊符号开头的自动导入API在`<script></script>`内能正常使用读取，但在`<template></template>`内则报出异常。
* 假如有一个自动检测导入的API：`export const $obj = { name: "张三" }`
* sfc单文件中
```vue
<template>
 {{ $obj.name }} <!-- 报错 Cannot read properties of undefined (reading 'name') -->
</template>
<script>
  console.log($obj.name) // 将正常输出 "张三"
</script>
```
* 这类情况是预期的吗
* `$`开头虽为约定内容中有所限制，但当其不冲突时应该可用

### Reproduction

..

### System Info

```Shell
win11  edge
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
`$` is reserved for global/internal APIs. Vue's template compiler will treat it differently. I'd suggest you to avoid using that convention
