### ISSUE TITLE
interfaces with a generic type that imported automatically has different behavior with manually

### ISSUE THREAD

**Issue by Ryuuki6602** [unplugin/unplugin-auto-import#442]
### Describe the bug

**interfaces with a generic type that imported automatically has different behavior with manually**

typings.d.ts
```
export interface Response<T>{
     data: T
}
```

vite.config.ts
```
{
     from: 'src/typings/response.d.ts',
     imports: ['Response'] 
     type: true,
},
```

auto-import.d.ts
```
declare global {
      export type { Response } from 'src/typings/response.d.ts'
}
```

However, when it comes into usage:
```
// an error occurs, it says that Type 'Response' is not generic.
const result: Response<string> = await fetch(url)
```

But if I import it manually:
```
// it works.
import type { Response } from '@typings/response'
const result: Response<string> = await fetch(url)
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-reqjfj?file=vite.config.ts,src%2Ftypings%2Fresponse.d.ts,src%2FApp.vue,package.json,src%2Fmain.ts&terminal=dev

### System Info

```Shell
System:
   OS: Windows 10 10.0.19045
   CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
   Memory: 5.85 GB / 15.95 GB
Binaries:
   Node: 20.9.0 - C:\DevTool\node\node.EXE
   Yarn: 1.22.21 - C:\DevTool\node\yarn.CMD
   npm: 10.1.0 - C:\DevTool\node\npm.CMD
   pnpm: 8.10.5 - C:\DevTool\node\pnpm.CMD
Browsers:
   Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.58)
   Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I don't think there is a way to solve this. The issue is because there is a built-in global type `Response` exists, and we can't override it. I'd suggest to rename the type to be more explicit.
