### ISSUE TITLE
Duplicated imports warning

### ISSUE THREAD

**Issue by rozsazoltan** [unplugin/unplugin-auto-import#462]
### Clear and concise description of the problem

I started using auto-import. I liked it a lot, so I quickly integrated Vue and VueUse as well. However, in my projects, instead of the native `toRefs()`, I use the enhanced `toRefs()` written by VueUse, which provides better reactivity. I don't want to rename it since it serves the same purpose as the native one, with the added benefit of accepting reactive values (e.g., computed values).

I didn't want to abandon the default templates (presets) because I like that with a community-maintained set, I don't have to declare every single Vue and VueUse function.

However, in the default presets, the `toRefs` from Vue is imported (which I don't have the ability to exclude from imports after requesting the presets).

```js
{
  imports: [
    'vue',
  ]
}
```

The `get`, `set`, and `toRefs` functions from VueUse are not imported by default (maybe by [vueuse-core.ts line 10](https://github.com/unplugin/unplugin-auto-import/blob/def80072fd9ed0bd2c8a17c6076251a68f468deb/src/presets/vueuse-core.ts#L10C3-L10C3)), which is not a problem since I can add these few details myself.

```js
{
  imports: [
    'vue',
    '@vueuse/core',
    {
      '@vueuse/core': [
        'set',
        'get',
        'toRefs',
      ],
    }
  ]
}
```

It actually works, but it's a bit "hacky," which Vite also warns about, as two `toRefs` functions are imported: 

```
Duplicated imports "toRefs", the one from "vue" has been ignored and "@vueuse/core" is used
```

### Suggested solution

Yes, a solution would be to rename the `toRefs` to something else using an alias, but I wouldn't like to do that because it's essentially the same Vue function, just enhanced. So, I want to exclude the native Vue `toRefs` from imports (without having to declare all Vue functions again, except for `toRefs`).

I couldn't find an option for exclusion. If there is one, please share it with me!

When it comes to imports, I would like to reference the "vue" preset in some structure and put the default `toRefs` function, which is included by default and is to be imported, on a blacklist. This way, my `toRefs` loaded from my @vueuse/core would no longer result in duplication.

```js
{
  imports: [
    'vue',
    '@vueuse/core',
    {
      'vue': [
        ['toRefs', false], // Here, "false" would represent the exclude, but this is just a quick adhoc idea.
      ],
      '@vueuse/core': [
        'set',
        'get',
        'toRefs',
      ],
    }
  ]
}
```

### Additional context

The issue arises because I don't want to call `toRefs` differently since it's `toRefs` and does the same thing both from Vue and VueUse. The difference lies in the fact that the one from VueUse accepts reactive variables, making it more versatile than the native solution.

As they do the same thing, it doesn't make sense to use both in the same project. Therefore, I either stick with the Vue one or the VueUse one, and I'd like to adhere to the original package naming (which is probably identical because the creator intended it to be used as a replacement for the original function).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SimonEast** [comment]
I'm hitting this same warning, also. 

I have two modules in my repo that both export a function we'll call `func()`.

- moduleA.func()
- moduleB.func()

I'd like to still use auto-import for both modules (they have lots of other useful functions) but be able to "ignore" or somehow exclude the one  function I don't want auto-imported (e.g. `moduleA.func()`), to avoid this clash.

How else is one supposed to work around this issue without modifying the module (which is not always possible, and would constitute a breaking change to its API)?

Maybe I have to "ignore" this function (which would presumably ignore it across both modules) and then somehow configure it manually?

----

*UPDATE:* The `ignore: ['func']` setting wasn't working for me, so I dug further in with AI help and found one of the modules exporting the same function twice, like this:

```js
export { func as default, func }
```

I removed one of these exports (the named one, keeping the default) and the AutoImport duplicate warning went away. This is a breaking change to my module (changing its public API), but thankfully in this case I can deal with that for now.
