### ISSUE TITLE
How to transform package code in node_modules？

### ISSUE THREAD

**Issue by Edge00** [unplugin/unplugin-auto-import#468]
### Describe the bug

default value of exclude is 
```
[/node_modules/, /\.git/]
```
We have a monorepo that target package is in node_modules (soft link). How to make this package be transformed.

### Reproduction

-

### System Info

```Shell
mac
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mustafa0x** [comment]
I have this question.

**Comment by lgzhang** [comment]
I have this question too. Can auto import from node_modules?

**Comment by lgzhang** [comment]
I have this question too. Can auto import from node_modules?
