### ISSUE TITLE
How to exclude a file in the dirs configuration folder?

### ISSUE THREAD

**Issue by yourVictor** [unplugin/unplugin-auto-import#475]
### Clear and concise description of the problem

How to exclude a file in the dirs configuration folder?

### Suggested solution
```
autoImport({
    imports: ['vue', 'pinia'],
    dirs: [
      resolve(__dirname, 'src/apis')
    ],
    exclude: [/node_modules/, /\.git/], // how to exclude a file in src/apis/
    dts: resolve(__dirname, 'src/auto-imports.d.ts')
  }),
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Asim-Tahir** [comment]
`dirs` option use [`minimatch`](https://github.com/isaacs/minimatch) under the hood. In minimatch [use negative pattern prefix](https://github.com/isaacs/minimatch?tab=readme-ov-file#comparisons-to-other-fnmatchglob-implementations)(`!`) to exclude files;

```ts
autoImport({
  imports: ['vue', 'pinia'],
  dirs: [
    resolve(__dirname, 'src/apis'),
    "!src/api/excludeFile.ts", // You don't have to use `path.resolve`
    // `!${resolve(__dirname, 'src/api/excludeFile.ts')}` // but if you prefer to use `path.resolve` you can use it like this
  ],
  exclude: [/node_modules/, /\.git/], // how to exclude a file in src/apis/
  dts: resolve(__dirname, 'src/auto-imports.d.ts')
}),
```

**Comment by lgzhang** [comment]
@antfu Excuse me.I have this question too. Can auto import from node_modules?

**Comment by Asim-Tahir** [comment]
@lgzhang yes you can. unplugin-auto-import` has multiple presets for the most used npm packages. If these are not fit for you. You can still import npm packages via the `imports` field in the vite plugin options. If you still have problems, let me know which package you want to use via auto-import.
