### ISSUE TITLE
eslint最新版本8.57.0中配置eslint.config.js，无法处理json的导入

### ISSUE THREAD

**Issue by yi-boide** [unplugin/unplugin-auto-import#487]
### Clear and concise description of the problem

eslint最新版本8.57.0中配置eslint.config.js，无法处理json的导入，需要更改生成的eslintrc的导出，使其支持导出为js，并且将生成的内容进行默认导出
```
eslintrc: {
          enabled: true, // Default `false`
          filepath: './.eslintrc-auto-import.json',
          globalsPropValue: true 
        }
```

### Suggested solution

```
eslintrc: {
          enabled: true, // Default `false`
          filepath: './.eslintrc-auto-import.js',
          globalsPropValue: true
        }
```
自动判断若是filepath是js结尾的，那么就给他生成默认导出，如下：
```
export default {
  "globals": {
    "Component": true,
    "ComponentPublicInstance": true,
    }
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zjtt** [comment]
这样引入就可以了 extends: [path.resolve(__dirname, './.eslintrc-auto-import.json')

**Comment by yi-boide** [comment]
> 这样引入就可以了 extends: [path.resolve(__dirname, './.eslintrc-auto-import.json')

现在可以直接导出为.cjs,.mjs了
