### ISSUE TITLE
在 rspack 中导致 SFC 样式失效

### ISSUE THREAD

**Issue by l246804** [unplugin/unplugin-auto-import#502]
### Describe the bug

在 `rspack` 项目中注册 `auto-import` 插件后导致 `SFC` 文件样式失效，取消注册后正常。

操作步骤：
1. 通过命令 `pnpm create rsbuild@latest` 创建 `vue3` 项目模板
2. 进入项目安装 `unplugin-auto-import`
3. 在 `rsbuild.config.ts` 中的 `tools.rspack.plugins` 注册 `unplugin-auto-import/rspack` 插件

### Reproduction

https://codesandbox.io/p/devbox/rspack-demo-4g45nx?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwqbh61p00073j6fd65ux3fi%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwqbh61p00023j6f784az1m2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwqbh61p00043j6f6xk64acp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwqbh61p00063j6fgc0jid03%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwqbh61p00023j6f784az1m2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqbh61p00013j6fk36q11k6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clwqbh61p00023j6f784az1m2%2522%252C%2522activeTabId%2522%253A%2522clwqbh61p00013j6fk36q11k6%2522%257D%252C%2522clwqbh61p00063j6fgc0jid03%2522%253A%257B%2522id%2522%253A%2522clwqbh61p00063j6fgc0jid03%2522%252C%2522activeTabId%2522%253A%2522clwqblm6500fc3j6fgn1bc9wi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clwqblm6500fc3j6fgn1bc9wi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clwqbh61p00043j6f6xk64acp%2522%253A%257B%2522id%2522%253A%2522clwqbh61p00043j6f6xk64acp%2522%252C%2522activeTabId%2522%253A%2522clwqbkar400dq3j6fotybmd2k%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwqbkar400dq3j6fotybmd2k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwqbkb3v0036dihudvn80fyu%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.87 GB / 15.66 GB
  Binaries:
    Node: 20.11.1 - ~\AppData\Local\pnpm\node.EXE
    npm: 10.2.4 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.13.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by l246804** [comment]
## 注册插件后
![image](https://github.com/unplugin/unplugin-auto-import/assets/53589602/ed89fd34-a4b0-4658-907c-8fb0902bf7ca)

## 取消注册插件后
![image](https://github.com/unplugin/unplugin-auto-import/assets/53589602/d1862abf-a28a-4ccb-a048-5463b1d66faa)

**Comment by PPPPigggg** [comment]
一样的问题，现在有什么解决方案吗

**Comment by l246804** [comment]
> 一样的问题，现在有什么解决方案吗

由于是新模板，我把插件删了手动补全了所有导入😂。

**Comment by Yusoo** [comment]
一样，rsbuild 0.7 以上就会有问题
