### ISSUE TITLE
don't collect empty export like export { }

### ISSUE THREAD

**Issue by pawover** [unplugin/unplugin-auto-import#504]
当用户开启 vscode setting `source.organizeImports` 时，`export {}` 会被格式化为 `export { }`，当数量超过2个时，控制台会收到警告 `WARN  Duplicated imports "", the one from "xxx/xxx.ts" has been ignored and "xxx/xxx.ts" is used`

在 `.ts` 文件中使用 `export {}` 是有意义的，配合 `declare global` 做到全局类型声明定义

我希望在 vscode 修复这个问题之前忽略收集 `export { }` ，现有配置选项中该如何配置？

**Comment by Jansschen** [comment]
可以请教一下怎么弄的吗？

**Comment by Jansschen** [comment]
![image](https://github.com/user-attachments/assets/7b773ba0-3734-4eab-b5ff-d2177a35d02b)
我也遇到了类似的问题

**Comment by pawover** [comment]
我是通过修改文件名，然后正则匹配只导出需要的文件
