### ISSUE TITLE
viteOptimizeDeps was set to true, causing some variables that were previously automatically imported to appear undefined

### ISSUE THREAD

**Issue by laterdayi** [unplugin/unplugin-auto-import#514]
### Describe the bug

viteOptimizeDeps was set to true, causing some variables that were previously automatically imported to appear undefined

![image](https://github.com/user-attachments/assets/294744be-226a-4a5f-bdc9-2da6bbb91fcc)

----

![image](https://github.com/user-attachments/assets/239d406c-399e-4357-beef-118e19a9adf0)

----

![image](https://github.com/user-attachments/assets/e4a0b000-a823-4bd7-99c5-dde89feb6946)

Before 0.18.0, it is normal, how should I modify it to make sure it works

pnpm run  hint standardVars undefined
### Reproduction

[demo.zip](https://github.com/user-attachments/files/16249394/demo.zip)

### System Info

```Shell
  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 7730U with Radeon Graphics
    Memory: 3.30 GB / 14.83 GB
  Binaries:
    Node: 20.15.0 - E:\node\node.EXE
    Yarn: 1.22.22 - E:\npm-global\yarn.CMD
    npm: 10.7.0 - E:\node\npm.CMD
    pnpm: 9.5.0 - E:\npm-global\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (126.0.2592.87)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by laterdayi** [comment]
[demo.zip](https://github.com/user-attachments/files/16249394/demo.zip)

**Comment by geedys** [comment]
I have the same problem.There were no issues prior to version 0.17.8.

**Comment by laterdayi** [comment]
Me too, I guess it is caused by 'viteOptimizeDeps: true', but I don't know how to fix it

**Comment by CharleeWa** [comment]
Hello All, this may not be what the author recommends, but have you tried explicitly configuring this attribute?

```ts
AutoImport({
  viteOptimizeDeps: false
})
```

**Comment by tarcyys** [comment]
> Hello All, this may not be what the author recommends, but have you tried explicitly configuring this attribute?
> 
> ```ts
> AutoImport({
>   viteOptimizeDeps: false
> })
> ```

 This can solve the problem, but if it is set to true, how do you solve this problem
