### ISSUE TITLE
How to correctly configure the json or js generated by eslintrc in eslint.config v9 version

### ISSUE THREAD

**Issue by ubuding** [unplugin/unplugin-auto-import#515]
I want eslint to check whether my usage is correct when submitting the code. For example, when I write computed(0) eslint will report an error

**Comment by akinoccc** [comment]
+1

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by magicalTom** [comment]
貌似和我遇到了同样的问题
这样操作试试：
<img width="687" alt="image" src="https://github.com/user-attachments/assets/458ca8ba-a5e8-4d2a-bdc5-da9ef66b35e3">
