### ISSUE TITLE
support `commentsDisable` in unimport

### ISSUE THREAD

**Issue by baixiaoyu2997** [unplugin/unplugin-auto-import#527]
### Clear and concise description of the problem

`// @unimport-disable` not work

### Suggested solution

support `commentsDisable` in unimport

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
It should work I think. Can you provide a repro?

**Comment by baixiaoyu2997** [comment]
i'm using next.js ,   it works,  need restart dev server
