### ISSUE TITLE
What specific conditions or settings are effecting wether the "dirs" option works or not?

### ISSUE THREAD

**Issue by elbbub** [unplugin/unplugin-auto-import#535]
I've just been aware the option "dirs" not working in my case. Any clues?
![Screenshot from 2024-10-03 04-03-14](https://github.com/user-attachments/assets/078cb212-b886-4913-924e-044d8137164e)
![Screenshot from 2024-10-03 18-59-15](https://github.com/user-attachments/assets/97223315-03f8-4aea-bbe3-28a72b08560e)

**Comment by WxhShine** [comment]
Hello, How was it solved? I also encountered this problem

**Comment by lisonge** [comment]
I do not know why it not working, but reboot vite server can work for me
