### ISSUE TITLE
Can we have `Write Mode`?

### ISSUE THREAD

**Issue by cyrilluce** [unplugin/unplugin-auto-import#539]
### Clear and concise description of the problem

When project went bigger, and co-develop with many people, we want to remove unplugin. 

- Unplugin is awesome for small projects, but awkful for big one, and may have many conflict components. 
- Implicit import will increase debug complexity.

Manually edit source code is waste life.

### Suggested solution

Add one time write mode, save the transformed code (added import statements) to source code.

Currently I wrote scripts for this job, but I think it should be better implement in this plugin

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jack-allocate** [comment]
@cyrilluce could you share the scripts you wrote for this? I have a similar usecase

**Comment by antfu** [comment]
I have this eslint plugin might help it: https://github.com/antfu/eslint-plugin-unimport

**Comment by cyrilluce** [comment]
> @cyrilluce could you share the scripts you wrote for this? I have a similar usecase

Sure, https://gist.github.com/cyrilluce/1776509b96717fb1bb5d1d7a31a0cbe9
It's customized code, Maybe you need modify to run.

> I have this eslint plugin might help it: https://github.com/antfu/eslint-plugin-unimport
Finally I use vscode's `Add all missing imports` to resolve `auto-imports`

Maybe `unplugin-vue-components` should also add this feature
